Drop ir.rule check -move to click-odoo ?

diff --git a/bin/oca_run_tests b/bin/oca_run_tests
--- a/bin/oca_run_tests
+++ b/bin/oca_run_tests
@@ -22,28 +22,28 @@ unbuffer coverage run --include "${ADDONS_DIR}/*" --branch \
 
 TEST=$?
 
-{
-unbuffer $(which odoo || which openerp-server) shell \
-    -d ${PGDATABASE} << EOF
-from odoo.tools.safe_eval import safe_eval
-from odoo.osv import expression
-import logging
-_logger = logging.getLogger(__name__)
-eval_context = env['ir.rule']._eval_context()
-for rule in env['ir.rule'].search([]):
-    try:
-        dom = safe_eval(rule.domain_force, eval_context) if rule.domain_force else []
-        dom = expression.normalize_domain(dom)
-        env[rule.model_id.model].search(dom)
-    except:
-        _logger.exception('Rule %s (%s) failed', rule.name, rule.get_external_id()[rule.id])
-        raise
-EOF
- } | tee >> /tmp/odoo.out
-TEST2=$?
-if [ -z "$TEST2" ] && (( $TEST == 0)); then
-     TEST = $TEST2
-fi
+# {
+# unbuffer $(which odoo || which openerp-server) shell \
+#     -d ${PGDATABASE} << EOF
+# from odoo.tools.safe_eval import safe_eval
+# from odoo.osv import expression
+# import logging
+# _logger = logging.getLogger(__name__)
+# eval_context = env['ir.rule']._eval_context()
+# for rule in env['ir.rule'].search([]):
+#     try:
+#         dom = safe_eval(rule.domain_force, eval_context) if rule.domain_force else []
+#         dom = expression.normalize_domain(dom)
+#         env[rule.model_id.model].search(dom)
+#     except:
+#         _logger.exception('Rule %s (%s) failed', rule.name, rule.get_external_id()[rule.id])
+#         raise
+# EOF
+#  } | tee >> /tmp/odoo.out
+# TEST2=$?
+# if [ -z "$TEST2" ] && (( $TEST == 0)); then
+#      TEST = $TEST2
+# fi
 
 if [[ ! -z "${PR_NUMBER}" ]]; then
     # https://github.com/actions/checkout/issues/766
